### ISSUE TITLE
Dealing with undefined callback for a mysql command

### ISSUE THREAD

**Issue by cheolgook** [building5/cls-mysql#1]
Most of the mysql commands would have callback passed in to inspect the result or error, but for `mysql.end()` practically it's not required since `node-mysql` is testing if the callback is there or not before calling it. And if we call the `mysql.end()` without a callback, it'll end up like this:

    /blah/node_modules/continuation-local-storage/context.js:97
          throw exception;
                ^
    TypeError: Cannot call method 'apply' of undefined
        at Quit._callback (/blah/node_modules/continuation-local-storage/context.js:91:17)
        at Quit.Sequence.end (/blah/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
        at Protocol.end (/blah/node_modules/mysql/lib/protocol/Protocol.js:99:24)
        at Socket.<anonymous> (/blah/node_modules/mysql/lib/Connection.js:102:28)
        at Socket.EventEmitter.emit (events.js:117:20)
        at _stream_readable.js:920:16
        at /blah/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
        at process._tickDomainCallback (node.js:459:13)
        at process.fallback (/blah/node_modules/continuation-local-storage/node_modules/async-listener/index.js:529:15)

So `cls-mysql` should be binding the `Sequence`'s callback only if there's one. I can make a pull request pretty soon if it makes sense.

**Comment by leedm777** [comment]
Sounds reasonable.  I'll look for your PR. If your PR includes a passing test, even better :-)

**Comment by leedm777** [comment]
Fixed in v1.0.3. Thanks for the PR!
